- name: installing redis repo
  ansible.builtin.yum: 
    name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm  
    state: installed
    disable_gpg_check: true

- name: enabling redis 6.2 version
  ansible.builtin.shell: yum module enable redis:remi-6.2 -y

- name: installing redis 6.2
  ansible.builtin.yum: 
    name: redis
    state: installed


- name: replacing redis local address to 0.0.0.0 in redis.conf
  ansible.builtin.replace:
    path: /etc/redis.conf 
    regexp: '127.0.0.1'
    replace: '0.0.0.0'
    
- name: replacing redis local address to 0.0.0.0 in redis.conf 2
  ansible.builtin.replace:
    path: /etc/redis/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: enable and restart redis
  ansible.builtin.systemd:
    name: redis
    state: restarted
    enabled: true