- name: Copy conf file
  ansible.builtin.copy:
    src: /roles/mongodb/files/mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo
- name: installing mongo db org
  ansible.builtin.yum:
    name: mongodb-org
    state: latest
- name: replacing mongod locahost to 0.0.0.0
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'
- name: enable and restart mongodb
  ansible.builtin.systemd:
    name: mongodb
    state: restarted
    enabled: true





echo -e "${color}installing mongo db org${nocolor}"
yum install mongodb-org -y &>>/tmp/mongodb.log
## need to change default ip to 0.0.0.0
echo -e "${color}replacing mongod locahost to 0.0.0.0${nocolor}"
sed -i 's/127.0.0.1/0.0.0.0/' /etc/mongod.conf

systemctl enable mongod 
systemctl restart mongod  &>>/tmp/mongodb.log
echo -e "${color}mongo db started${nocolor}"