- name: installing maven
  ansible.builtin.yum:
    name: maven
    state: installed

- name: importing application setup role
  ansible.builtin.import_role:
    name: common
    tasks_from: application_presetup

- name: maven clean package
  ansible.builtin.shell: mvn clean package
  args:
    chdir: /app

- name: install dependencies
  ansible.builtin.shell: mv target/shipping-1.0.jar shipping.jar 
  args:
    chdir: /app

- name: Copy service file 
  ansible.builtin.copy:
    src: "shipping.service"
    dest: /etc/systemd/system/shipping.service

- name: enable and restart {{ component }}
  ansible.builtin.systemd:
    name: "shipping"
    state: started
    enabled: true
    daemon-reload: true


- name: installing mysql community version
  ansible.builtin.yum:
    name: mysql
    state: installed

- name: mysql - Load schema
  ansible.builtin.shell: mysql -h mysql-dev.devops23.store -uroot -pRoboShop@1 < /app/schema/shipping.sql


- name: restart shipping
  ansible.builtin.systemd:
   name: shipping
   state: restarted