- name: add user roboshop
  ansible.builtin.user:
    name: roboshop

- name: Removing old app dir
  ansible.builtin.file:
    path: /app
    state: absent

- name: Create a directory 
  ansible.builtin.file:
    path: /app
    state: directory

- name: Unarchive a file that needs to be downloaded 
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/{{ component }}.zip
    dest: /app
    remote_src: yes
    chdir: /app