- name: configuring nodejs repos and installing nodejs
  ansible.builtin.shell:
    name: https://rpm.nodesource.com/setup_lts.x | bash
    state: installed
    disable_gpg_check: true

- name: application presetup
  ansible.builtin.include_tasks:
    file: application_presetup.yml

- name: installing nodejs dependencies npm
  ansible.builtin.shell: npm install
    #chmod: /app


- name: systemd setup
  ansible.builtin.include_tasks:
    file: systemd.yml


