- name: configuring nodejs repos and installing nodejs
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash
   
- name: install nodejs
  ansible.builtin.yum:
    name: nodejs
    state: installed

- name: application presetup
  ansible.builtin.include_tasks:
    file: application_presetup.yml

- name: installing nodejs dependencies npm
  ansible.builtin.shell: npm install
  args:
    chdir: /app


- name: systemd setup
  ansible.builtin.include_tasks:
    file: systemd.yml


